name: Docs CI

on:
  release:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: 1. Checkout
        uses: actions/checkout@v2
      - name: 2. Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: 3. Install dependencies and build 🔧
        run: |
          cd site
          rm -rf node_modules
          npm install ydoc -g
          yarn --frozen-lockfile
          ydoc build
        env:
          CI: true
      - name: 4. script deploy
        env:
          DEPLOY_ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          PUBLISH_BRANCH: site
          PUBLISH_DIR: ./_site
          CNAME: shirojs.buession.com
        run: |
          cd site
          chmod +x ./scripts/deploy.sh
          bash ./scripts/deploy.sh